In [1]:
import pandas as pd
from sodapy import Socrata
from dotenv import load_dotenv
import os

In [2]:
from dotenv import load_dotenv
import os

load_dotenv()

APP_TOKEN = os.getenv("SOCRATA_APP_TOKEN")

print("Token loaded:", APP_TOKEN is not None)

Token loaded: True

In [3]:
client = Socrata(
    "data.cambridgema.gov",
    APP_TOKEN,
    timeout=30
)

In [4]:
DATASET_ID = "3gki-wyrb"

results = list(client.get_all(DATASET_ID))

len(results)

11900

In [5]:
df = pd.DataFrame.from_records(results)

In [6]:
df.head()

,date_time,id,type,subtype,location,description,last_updated
0,2025-03-06T01:07:00.000,25001925,INCIDENT,LARCENY FROM BUILDING C266 S20,NEWPORT RD,Police responded to the 0 block of Newport Rd ...,2025-03-11T09:35:52.000
1,2025-03-06T01:56:00.000,25001926,INCIDENT,"MOTOR VEH, LARCENY OF C266 S28",MASSACHUSETTS AVE,Police responded to the 400 block of Massachus...,2025-03-11T09:35:52.000
2,2025-03-06T09:15:00.000,25001928,INCIDENT,B&E MV / BOAT NIGHTTIME FOR FELONY C266 S16,IRVING ST,Police responded to the 0 block of Irving Stre...,2025-03-11T09:35:52.000
3,2025-03-06T10:01:00.000,25001929,INCIDENT,LARCENY UNDER $1200 C266 S30(1),MASSACHUSETTS AVE & WESTERN AVE,A Cambridge resident came to the Central Squar...,2025-03-11T09:35:52.000
4,2025-03-06T10:02:00.000,25001930,INCIDENT,SHOPLIFTING BY ASPORTATION C266 S30A,MASSACHUSETTS AVE,Police responded to the 500 block of Massachus...,2025-03-11T09:35:52.000

In [7]:
df.shape

(11900, 7)

In [8]:
df.columns

Index(['date_time', 'id', 'type', 'subtype', 'location', 'description',
       'last_updated'],
      dtype='str')

In [9]:
df.columns

Index(['date_time', 'id', 'type', 'subtype', 'location', 'description',
       'last_updated'],
      dtype='str')

In [10]:
results = client.get_all(DATASET_ID )

df = pd.DataFrame.from_records(results)

print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

Rows: 11900
Columns: 7

,date_time,id,type,subtype,location,description,last_updated
0,2025-03-06T01:07:00.000,25001925,INCIDENT,LARCENY FROM BUILDING C266 S20,NEWPORT RD,Police responded to the 0 block of Newport Rd ...,2025-03-11T09:35:52.000
1,2025-03-06T01:56:00.000,25001926,INCIDENT,"MOTOR VEH, LARCENY OF C266 S28",MASSACHUSETTS AVE,Police responded to the 400 block of Massachus...,2025-03-11T09:35:52.000
2,2025-03-06T09:15:00.000,25001928,INCIDENT,B&E MV / BOAT NIGHTTIME FOR FELONY C266 S16,IRVING ST,Police responded to the 0 block of Irving Stre...,2025-03-11T09:35:52.000
3,2025-03-06T10:01:00.000,25001929,INCIDENT,LARCENY UNDER $1200 C266 S30(1),MASSACHUSETTS AVE & WESTERN AVE,A Cambridge resident came to the Central Squar...,2025-03-11T09:35:52.000
4,2025-03-06T10:02:00.000,25001930,INCIDENT,SHOPLIFTING BY ASPORTATION C266 S30A,MASSACHUSETTS AVE,Police responded to the 500 block of Massachus...,2025-03-11T09:35:52.000

In [11]:
from extract import extract_data

In [12]:
df = extract_data()

print(df.shape)
df.head()

01:36:52.973 | INFO    | prefect - Starting temporary server on http://127.0.0.1:8753
See https://docs.prefect.io/v3/concepts/server#how-to-guides for more information on running a dedicated Prefect server.

/opt/anaconda3/envs/crime_pipeline/lib/python3.12/logging/__init__.py:1962: UserWarning: Logger 'prefect.task_runs' attempted to send logs to the API without a flow run id. The API log handler can only send logs within flow run contexts unless the flow run id is manually provided. Set PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW=ignore to suppress this warning.
  self.logger.log(level, msg, *args, **kwargs)

01:37:07.138 | INFO    | Task run 'extract_data' - Finished in state Completed()

(11900, 7)

,date_time,id,type,subtype,location,description,last_updated
0,2025-03-06T01:07:00.000,25001925,INCIDENT,LARCENY FROM BUILDING C266 S20,NEWPORT RD,Police responded to the 0 block of Newport Rd ...,2025-03-11T09:35:52.000
1,2025-03-06T01:56:00.000,25001926,INCIDENT,"MOTOR VEH, LARCENY OF C266 S28",MASSACHUSETTS AVE,Police responded to the 400 block of Massachus...,2025-03-11T09:35:52.000
2,2025-03-06T09:15:00.000,25001928,INCIDENT,B&E MV / BOAT NIGHTTIME FOR FELONY C266 S16,IRVING ST,Police responded to the 0 block of Irving Stre...,2025-03-11T09:35:52.000
3,2025-03-06T10:01:00.000,25001929,INCIDENT,LARCENY UNDER $1200 C266 S30(1),MASSACHUSETTS AVE & WESTERN AVE,A Cambridge resident came to the Central Squar...,2025-03-11T09:35:52.000
4,2025-03-06T10:02:00.000,25001930,INCIDENT,SHOPLIFTING BY ASPORTATION C266 S30A,MASSACHUSETTS AVE,Police responded to the 500 block of Massachus...,2025-03-11T09:35:52.000

In [13]:
from validate import validate_data

validated_df = validate_data(df)

validated_df.head()

All expected columns are present.
Data validation completed.

/opt/anaconda3/envs/crime_pipeline/lib/python3.12/logging/__init__.py:1962: UserWarning: Logger 'prefect.task_runs' attempted to send logs to the API without a flow run id. The API log handler can only send logs within flow run contexts unless the flow run id is manually provided. Set PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW=ignore to suppress this warning.
  self.logger.log(level, msg, *args, **kwargs)

01:37:07.240 | INFO    | Task run 'validate_data' - Finished in state Completed()

,date_time,id,type,subtype,location,description,last_updated
0,2025-03-06 01:07:00,25001925,INCIDENT,LARCENY FROM BUILDING C266 S20,NEWPORT RD,Police responded to the 0 block of Newport Rd ...,2025-03-11T09:35:52.000
1,2025-03-06 01:56:00,25001926,INCIDENT,"MOTOR VEH, LARCENY OF C266 S28",MASSACHUSETTS AVE,Police responded to the 400 block of Massachus...,2025-03-11T09:35:52.000
2,2025-03-06 09:15:00,25001928,INCIDENT,B&E MV / BOAT NIGHTTIME FOR FELONY C266 S16,IRVING ST,Police responded to the 0 block of Irving Stre...,2025-03-11T09:35:52.000
3,2025-03-06 10:01:00,25001929,INCIDENT,LARCENY UNDER $1200 C266 S30(1),MASSACHUSETTS AVE & WESTERN AVE,A Cambridge resident came to the Central Squar...,2025-03-11T09:35:52.000
4,2025-03-06 10:02:00,25001930,INCIDENT,SHOPLIFTING BY ASPORTATION C266 S30A,MASSACHUSETTS AVE,Police responded to the 500 block of Massachus...,2025-03-11T09:35:52.000

In [14]:
from transform import transform_data

transformed_df = transform_data(validated_df)

transformed_df.head()

/opt/anaconda3/envs/crime_pipeline/lib/python3.12/logging/__init__.py:1962: UserWarning: Logger 'prefect.task_runs' attempted to send logs to the API without a flow run id. The API log handler can only send logs within flow run contexts unless the flow run id is manually provided. Set PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW=ignore to suppress this warning.
  self.logger.log(level, msg, *args, **kwargs)

01:37:07.305 | INFO    | Task run 'transform_data' - Finished in state Completed()

,date_time,id,type,subtype,location,description,last_updated,year,month,day,hour
0,2025-03-06 01:07:00,25001925,INCIDENT,LARCENY FROM BUILDING C266 S20,NEWPORT RD,Police responded to the 0 block of Newport Rd ...,2025-03-11T09:35:52.000,2025,3,6,1
1,2025-03-06 01:56:00,25001926,INCIDENT,"MOTOR VEH, LARCENY OF C266 S28",MASSACHUSETTS AVE,Police responded to the 400 block of Massachus...,2025-03-11T09:35:52.000,2025,3,6,1
2,2025-03-06 09:15:00,25001928,INCIDENT,B&E MV / BOAT NIGHTTIME FOR FELONY C266 S16,IRVING ST,Police responded to the 0 block of Irving Stre...,2025-03-11T09:35:52.000,2025,3,6,9
3,2025-03-06 10:01:00,25001929,INCIDENT,LARCENY UNDER $1200 C266 S30(1),MASSACHUSETTS AVE & WESTERN AVE,A Cambridge resident came to the Central Squar...,2025-03-11T09:35:52.000,2025,3,6,10
4,2025-03-06 10:02:00,25001930,INCIDENT,SHOPLIFTING BY ASPORTATION C266 S30A,MASSACHUSETTS AVE,Police responded to the 500 block of Massachus...,2025-03-11T09:35:52.000,2025,3,6,10

In [15]:
transformed_df[[
    "date_time",
    "year",
    "month",
    "day",
    "hour"
]].head()

            date_time  year  month  day  hour
0 2025-03-06 01:07:00  2025      3    6     1
1 2025-03-06 01:56:00  2025      3    6     1
2 2025-03-06 09:15:00  2025      3    6     9
3 2025-03-06 10:01:00  2025      3    6    10
4 2025-03-06 10:02:00  2025      3    6    10

In [16]:
from load import load_into_postgres

In [17]:
load_into_postgres(transformed_df)

Data loaded into PostgreSQL.

/opt/anaconda3/envs/crime_pipeline/lib/python3.12/logging/__init__.py:1962: UserWarning: Logger 'prefect.task_runs' attempted to send logs to the API without a flow run id. The API log handler can only send logs within flow run contexts unless the flow run id is manually provided. Set PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW=ignore to suppress this warning.
  self.logger.log(level, msg, *args, **kwargs)

01:37:08.044 | INFO    | Task run 'load_into_postgres' - Finished in state Completed()

In [18]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5433/crime_db"
)

test_df = pd.read_sql(
    "SELECT * FROM cpd_incidents LIMIT 10",
    engine
)

test_df

,date_time,id,type,subtype,location,description,last_updated,year,month,day,hour
0,2025-03-06 01:07:00,25001925,INCIDENT,LARCENY FROM BUILDING C266 S20,NEWPORT RD,Police responded to the 0 block of Newport Rd ...,2025-03-11T09:35:52.000,2025,3,6,1
1,2025-03-06 01:56:00,25001926,INCIDENT,"MOTOR VEH, LARCENY OF C266 S28",MASSACHUSETTS AVE,Police responded to the 400 block of Massachus...,2025-03-11T09:35:52.000,2025,3,6,1
2,2025-03-06 09:15:00,25001928,INCIDENT,B&E MV / BOAT NIGHTTIME FOR FELONY C266 S16,IRVING ST,Police responded to the 0 block of Irving Stre...,2025-03-11T09:35:52.000,2025,3,6,9
3,2025-03-06 10:01:00,25001929,INCIDENT,LARCENY UNDER $1200 C266 S30(1),MASSACHUSETTS AVE & WESTERN AVE,A Cambridge resident came to the Central Squar...,2025-03-11T09:35:52.000,2025,3,6,10
4,2025-03-06 10:02:00,25001930,INCIDENT,SHOPLIFTING BY ASPORTATION C266 S30A,MASSACHUSETTS AVE,Police responded to the 500 block of Massachus...,2025-03-11T09:35:52.000,2025,3,6,10
5,2025-03-06 10:22:00,25001933,INCIDENT,B&E MV / BOAT NIGHTTIME FOR FELONY C266 S16,CLINTON ST,Police responded to the 0 block of Clinton st...,2025-03-11T09:35:52.000,2025,3,6,10
6,2025-03-06 10:27:00,25001932,ARREST,WARRANT ARREST REPORT,MASSACHUSETTS AVE,Police were patrolling the 600 block of Massac...,2025-03-11T09:35:52.000,2025,3,6,10
7,2025-03-06 10:46:00,25001934,INCIDENT,B&E NIGHTTIME FOR FELONY C266 S16,MASSACHUSETTS AVE,Police responded to a business on the 2300 blo...,2025-03-11T09:35:52.000,2025,3,6,10
8,2025-03-06 11:23:00,25001935,INCIDENT,"FIREARM, CARRY WITHOUT LICENSE C269 S10(A)",MASSACHUSETTS AVE,Police responded to the 500 block of Massachus...,2025-03-11T09:35:52.000,2025,3,6,11
9,2025-03-06 12:34:00,25001936,INCIDENT,THREAT TO COMMIT CRIME C275 S2,MOUNT AUBURN ST,Police responded to the 300 block of Mount Aub...,2025-03-11T09:35:52.000,2025,3,6,12